
seed: 123
max_T: 309.99

model:
  target: arch.unet.UNet
  params:
    n_channels: 1
    scale_factor: 12
    ckpt_path:
#  ckpt_path: log_1/300.pth

train:
  # learning rate
  lr: 5e-5
  epochs: 300
  # save logging
  save_freq: 10000
  batch: [1, 1]
  num_workers: 1
  log_freq: [10, 10, 10]

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    sf: 12
    schedule_name: exponential
    schedule_kwargs:
      power_u: 0.2  # best
      power_eps: 0.3
    etas_end: 0.99
    steps: 15
    min_noise_level: 0.04
    normalize_input: True
    latent_flag: False

data:
  train:
    params:
      lr: ['D:\Desktop\微波模拟与超分辨率降尺度\模型结果数据\train\0.1']
      hr: ['D:\Desktop\微波模拟与超分辨率降尺度\模型结果数据\train\0.0083']
  val:
    params:
      lr: ['D:\Desktop\微波模拟与超分辨率降尺度\模型结果数据\test\0.1']
      hr: ['D:\Desktop\微波模拟与超分辨率降尺度\模型结果数据\test\0.0083']



